{% set name = "yq" %}
{% set version = "2.5.0" %}
{% set sha256 = "e9fd2aa32defcd051058e3b6f665873282aa4eed19e11b1db94fe70847535d4c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # github.com/sodre/yq:entry_points: replace scripts with entry-points
    - github_com__sodre__yq__entry_points.patch
    - github_com__sodre__yq__fix-jq-errcode.patch

build:
  number: 0
  noarch: python
  entry_points:
    - yq = yq:main
    - xq = yq:xq_cli
  script: 
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pyyaml >=3.11
    - xmltodict >=0.11.0
    - jq

test:
  requires:
    - pytest
  source_files:
    - test
  imports:
    - yq
  commands:
    - pytest test/test.py
    - yq --help
    - xq --help
    - test $(cat $RECIPE_DIR/meta.yaml | yq -r .package.name) = 'yq'

about:
  home: https://github.com/kislyuk/yq
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'jq wrapper for YAML and XML documents'

  doc_url: https://yq.readthedocs.io/en/latest/
  dev_url: https://github.com/kislyuk/yq

extra:
  recipe-maintainers:
    - sodre
