travis:
  secure:
    BINSTAR_TOKEN: PDJGxl/SHaO6/BmGeleS5DDAATcBATDTc3DyzHb5KP7CoJs+a39i+uojaxcOzmRf6HzxnRj854wdouMmlD/FRhFzhsD+6VbpYySB8U5O2rrEvUKe83HyHIn3WbwKiuWcXnurVfgHSlDwDP2gZvCv7Cl1TufukND5VrazgaaG7m9or4mVyVvaV42ZaA/b7oJlxuvnlIKAZP0o8+MUZYoxWaQAmae3T+vCncqLv5bA1/NKAjnmqqza+y4eTsqiik4hIfPDgOz0PCwLXg3WEAwV5GVv/U94yadNAfaIddFrnQlKCrDp5+YJCSMTOhsBYiVcwk/DGFKHxaq4V4KvFj9R1cN4u0kLzZC+0uv5gwjHAQ4fNfO7ucq9CWkBX79lNAKbQhqY5ECoC+DOkR3xI2lkEycKg6wxn8uaFm9e3AMmFT7nDwtuQchbqzqUCWn6SaX9oEyR5rf1h3tHa8tH9JE1lpP1WSWw2gBmUDnOF436C/ZsazCQXky1+192q08E7LCKu3bf/1O7m4viW/T0Pj7u3cc/SjFTDWaRJ+W2S6JyVfa+LkmBaBzuwUMI4fd8ljTZeKsbo9BS4lkiwClnuTc35QpSotlMWxcy5i3ylAj6dISQ02EbSb7uKhXDq3FtG2FHwd9Uz/f5Qq/HbQVxkvdwrRHPhiGBlnqs+/pRf+pHebY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
